config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"

  root to: "pages#welcome"
  resources :boardgames, only: %i[index new create]
  resources :players, only: %i[destroy]
  resources :users, only: %i[show new create edit update destroy]
  resources :parties, only: %i[show destroy update]
  resources :game_to_users, only: %i[destroy]

  resources :boardgames, only: :show do
    resources :game_to_users, only: %i[create]
    resources :players, only: :show
    resources :parties, only: %i[new create]
    resources :challenges, only: %i[new create]
  end

  resources :parties, only: [] do
    resources :players, only: %i[new create update]
  end

  resources :challenges, only: %i[index] do
    resources :achievements, only: %i[index new create update]
  end
end

app/models/achievement.rb
class Achievement < ApplicationRecord
  belongs_to :challenge
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/boardgame.rb
class Boardgame < ApplicationRecord
  has_many :parties, dependent: :destroy
  has_many :game_to_users, dependent: :destroy
  has_many :players, through: :parties
  has_many :users, through: :game_to_users
  has_many :challenges, dependent: :destroy

  validates :title, :description, :play_time, :age,
  :rating, :min_player, :max_player, :category, presence: true
  has_one_attached :photo

end

app/models/challenge.rb
class Challenge < ApplicationRecord
  belongs_to :boardgame
  has_many :achievements, dependent: :destroy
  validates :title, presence: true

  CATEGORY = %w[badge challenge].freeze
end

app/models/game_to_user.rb
class GameToUser < ApplicationRecord
  belongs_to :user
  belongs_to :boardgame
end

app/models/history.rb
class History < ApplicationRecord
  belongs_to :user
end

app/models/party.rb
class Party < ApplicationRecord
  belongs_to :boardgame
  has_many :players, dependent: :destroy
  has_many :users, through: :players
  validates :start_time, presence: true
  after_update :challenge_calcul_scores, if: -> { end_time.present? }
  after_update :challenge_calcul_victories, if: -> { end_time.present? }

  private

  def challenge_calcul_scores
    players.each do |player|
      boardgame.challenges.each do |challenge|
        next unless player.score >= challenge.score
        challenge.achievements.where(user: player.user).each do |achievement|
          achievement.update(completed: true)
          achievement.user.update(level: achievement.user.level += 1)
        end
      end
    end
  end

  def challenge_calcul_victories
    players.each do |player|
      boardgame.challenges.each do |challenge|
        next unless player.user.victories == challenge.victory
        challenge.achievements.where(user: player.user).each do |achievement|
          achievement.update(completed: true)
          achievement.user.update(level: achievement.user.level += 1)
        end
      end
    end
  end
  
end

app/models/player.rb
class Player < ApplicationRecord
  belongs_to :user
  belongs_to :party
  after_create :add_achivements

  def add_achivements
    party.boardgame.challenges.each do |challenge|
      Achievement.create(challenge:, user:)
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :players, dependent: :destroy
  has_many :parties, through: :players
  has_many :game_to_users, dependent: :destroy
  has_many :boardgames, through: :game_to_users
  has_many :achievements, dependent: :destroy
  has_many :challenges, through: :achievements

  validates :username, presence: true
  has_one_attached :avatar

  def boardgame_players(boardgame_id)
    parties_ids = parties.where(boardgame_id:).pluck(:id)
    user_ids    = Player.where(party_id: parties_ids).pluck(:user_id)
    User.where(id: user_ids)
  end

  def victories
    parties.select { |party| party.players.order(:score).last.user == self }.count
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def welcome
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @parties = current_user.parties
    @challenges = @user.challenges
    @achievements = @user.achievements.where(completed: true).group_by { |a| a.challenge.boardgame }
    @total_min = 0
    @total_hours = 0
    @total_days = 0
  end
end

app/helpers/achievements_helper.rb
module AchievementsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boardgames_helper.rb
module BoardgamesHelper
end

app/helpers/challenges_helper.rb
module ChallengesHelper
end

app/helpers/game_to_users_helper.rb
module GameToUsersHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ?
    content_for(:meta_title) : DEFAULT_META["meta_title"]
  end
  def meta_description
    content_for?(:meta_description) ?
    content_for(:meta_description) : DEFAULT_META["meta_description"]
  end
  def meta_image
    meta_image = (content_for?(:meta_image) ?
    content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ?
    meta_image : image_url(meta_image)
  end
end

app/helpers/parties_helper.rb
module PartiesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="fr">
  <head>
    <title>Time2play</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <meta >
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

     <!-- Chart JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.9.1/chart.min.js"></script>
    <!-- Chart JS Plugin for displaying text over chart -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/chartjs-plugin-datalabels/2.1.0/chartjs-plugin-datalabels.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/tsparticles-confetti@2.12.0/tsparticles.confetti.bundle.min.js"></script>
    <link rel="manifest" href="<%= asset_path 'manifest.json' %>">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,400;0,500;0,700;0,900;1,100&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=Raleway:wght@400;500;600;700&display=swap" rel="stylesheet">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= render 'shared/ios_pwa_links' %>
    <%= favicon_link_tag %>
  </head>

  <body>
    <% unless action_name == "welcome" %>
      <%= render "shared/tab_bar" %>
    <% end %>
    <%= yield %>
    <%= render "shared/flashes" %>
  </body>
</html>

app/views/pages/welcome.html.erb
<%= link_to boardgames_path do %>
  <div class="welcome" style="background-image: url('<%= image_path("dice.jpg") %>')">
    <p class="welcome-title">time<span class="two-title">2</span>play</p>
  </div>
<% end %>

app/views/shared/_card.html.erb
<%= link_to boardgame_path(boardgame), class: "text-decoration-none" do %>
  <div class="card-trip" style="background-image: url('<%= cl_image_path(boardgame.photo.key, crop: :fit) %>')">
  </div>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">

app/views/shared/_logout.html.erb
<div class="d-flex align-items-center justify-content-center mt-5">
  <%= link_to "Déconnexion",
  destroy_user_session_path,
  class: " btn btn-info fw-bold btn-sm logout #{ 'hidden' if user_signed_in? == false }",
  data: {turbo_method: :delete}%>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <i class="fa-solid fa-bars fa-lg"></i>
    </button>

    <%= link_to "TIME2PLAY", boardgames_path %>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Profil", user_path(current_user), class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Logout", destroy_user_session_path, class: "nav-link #{ 'hidden' if user_signed_in? == false }", data: {turbo_method: :delete}%>
          </li>
          <li class="nav-item dropdown">
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_tab_bar.html.erb
<div data-controller="tabbar-active" class="tab-bar d-flex align-items-center justify-content-center justify-content-evenly">
  <%= link_to boardgames_path, data: { tabbar_active_target: "tab1" } do %>
    <i class="fa-solid fa-indent fa-xl"></i>
  <% end %>
   <%= link_to challenges_path, data: { tabbar_active_target: "tab2" } do %>
    <i class="fa-solid fa-trophy fa-xl"></i>
  <% end %>
  <% if user_signed_in? %>
    <%= link_to user_path(current_user), data: { tabbar_active_target: "tab3" } do %>
      <i class="fa-solid fa-user fa-xl"></i>
    <% end %>
  <% else %>
    <%= link_to new_user_session_path, data: { tabbar_active_target: "tab4" } do %>
      <i class="fa-solid fa-user fa-xl"></i>
    <% end %>
  <% end %>
</div>