config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"

  root to: "pages#welcome"
  resources :boardgames, only: %i[index new create]
  resources :players, only: %i[destroy]
  resources :users, only: %i[show new create edit update destroy]
  resources :parties, only: %i[show destroy update]
  resources :game_to_users, only: %i[destroy]

  resources :boardgames, only: :show do
    resources :game_to_users, only: %i[create]
    resources :players, only: :show
    resources :parties, only: %i[new create]
    resources :challenges, only: %i[new create]
  end

  resources :parties, only: [] do
    resources :players, only: %i[new create update]
  end

  resources :challenges, only: %i[index] do
    resources :achievements, only: %i[index new create update]
  end
end

app/models/boardgame.rb
class Boardgame < ApplicationRecord
  has_many :parties, dependent: :destroy
  has_many :game_to_users, dependent: :destroy
  has_many :players, through: :parties
  has_many :users, through: :game_to_users
  has_many :challenges, dependent: :destroy

  validates :title, :description, :play_time, :age,
  :rating, :min_player, :max_player, :category, presence: true
  has_one_attached :photo

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :players, dependent: :destroy
  has_many :parties, through: :players
  has_many :game_to_users, dependent: :destroy
  has_many :boardgames, through: :game_to_users
  has_many :achievements, dependent: :destroy
  has_many :challenges, through: :achievements

  validates :username, presence: true
  has_one_attached :avatar

  def boardgame_players(boardgame_id)
    parties_ids = parties.where(boardgame_id:).pluck(:id)
    user_ids    = Player.where(party_id: parties_ids).pluck(:user_id)
    User.where(id: user_ids)
  end

  def victories
    parties.select { |party| party.players.order(:score).last.user == self }.count
  end
end

app/controllers/boardgames_controller.rb
class BoardgamesController < ApplicationController
  def index
    @boardgames = Boardgame.all
    if params[:query].present?
      keywords = params[:query].split(/\s+/) # Divise la recherche en mots individuels
      conditions = keywords.map { |keyword| "title ILIKE ?" }.join(" OR ")
      query_args = keywords.map { |keyword| "%#{keyword}%" }

      @boardgames = @boardgames.where(conditions, *query_args)
    end
  end

  def new
    @boardgame = Boardgame.new
  end

  def create
    @boardgame = Boardgame.new(boardgame_params)
    if @boardgame.save
      redirect_to boardgames_path(@boardgame)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @boardgame = Boardgame.find(params[:id])
    @players = @boardgame.players
    @parties = @boardgame.parties
    @challenges = @boardgame.challenges
    @challenge = Challenge.new
  end

  private

  def boardgame_params
    params.require(:boardgame).permit(:title, :description, :play_time, :age, :image,
    :rating, :min_player, :max_player, :category, :photo)
  end
end

app/helpers/boardgames_helper.rb
module BoardgamesHelper
end

app/views/boardgames/index.html.erb
<div class="container">
  <h1 class="title-page">Ludothèque</h1>
</div>
<%= render "boardgames/partials/search" %>

<div class="container">
  <div class="cards">
    <% @boardgames.each do |boardgame| %>
      <%= render "shared/card", boardgame: boardgame %>
    <% end %>
  </div>
</div>

<div id="lds-roller" class="d-none position-absolute top-50 start-50 translate-middle"><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div></div>

app/views/boardgames/show.html.erb
  <div class="container">
    <h1 class="title-page">Détails du jeu</h1>
  </div>
  <div class="show-marging">
  <div class="game-banner">
    <h2 class="mt-3 mb-3 game-title" ><%= @boardgame.title %></h2>
    <img class="show-img" src="<%= cl_image_path @boardgame.photo.key, height: 300, crop: :fit %>"/>
    <% if user_signed_in? %>
      <div class="add-flex">
        <% if current_user.boardgame_ids.include?(@boardgame.id) %>
        <%= link_to game_to_user_path(GameToUser.find_by(user:current_user, boardgame:@boardgame)), class: "remove-submit-btn-style btn-validate", data: {turbo_method: :delete} do %>
          <i class="fa-solid fa-circle-minus" style="color: #707070;"></i>
          <%= link_to "Jouer", boardgame_parties_path(@boardgame), data: {turbo_method: :post}, class: "new-game btn btn-info fw-bold" %>
        <% end %>
        <p class="grey">Supprimer de ma collection</p>
        <% else %>
          <%= link_to boardgame_game_to_users_path(@boardgame), class: "remove-submit-btn-style btn-validate", data: {turbo_method: :post} do %>
          <i class="fa-solid fa-circle-plus" style="color: #ffcd39;--fa-animation-duration: 2s; --fa-fade-opacity: 0.6;"></i>
        <% end %>
        <p>Ajouter le jeu à ma collection</p>
      <% end %>
      </div>
    <% end %>
  </div>

  <%# =============== GAME SECTION ===============%>
  <div class="game-container">
    <div class="">
        <div class="basic-game-info-container">
          <i class="fa-solid fa-people-group">  <%= @boardgame.min_player %> - <%= @boardgame.max_player %></i>
          <i class="fa-solid fa-child-reaching">  <%= @boardgame.age %>+</i>
          <i class="fa-regular fa-hourglass-half">  <%= @boardgame.play_time %> mn</i>
          <i class="fa-regular fa-star">  <%= @boardgame.rating %></i>
        </div>
        <p class="game-description"><%= @boardgame.description %></p>
    </div>
  </div>

<%# =============== PLAYERS SECTION ===============%>
<div class="boardgame-action">
  <div class="accordion accordion-flush" id="accordionFlushExample">
    <div class="accordion-item">
      <h2 class="accordion-header" id="flush-headingOne">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseOne" aria-expanded="false" aria-controls="flush-collapseOne">
          Ils y jouent
        </button>
      </h2>
      <div id="flush-collapseOne" class="accordion-collapse collapse" aria-labelledby="flush-headingOne" data-bs-parent="#accordionFlushExample">
        <div class="accordion-body accordion-background d-flex">
          <% if @players == [] %>
            <em>Pas de joueurs pour le moment.</em>
          <% else %>
            <% @players.take(3).each do |player| %>
              <div>
                <% if player.user.avatar.attached? %>
                  <%= cl_image_tag player.user.avatar.key, height: 40, width: 40, crop: :fit, class: "avatar" %>
                <% else %>
                    <%= cl_image_tag current_user.avatar.key, height: 40, width: 40, crop: :fit, class: "avatar" %>
                <% end %>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <%# =============== PARTIES SECTION ===============%>
  <div class="accordion accordion-flush" id="accordionFlushExample">
    <div class="accordion-item">
      <h2 class="accordion-header" id="flush-headingTwo">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseTwo" aria-expanded="false" aria-controls="flush-collapseTwo">
          Mes dernières parties
        </button>
      </h2>
      <div id="flush-collapseTwo" class="accordion-collapse collapse" aria-labelledby="flush-headingTwo" data-bs-parent="#accordionFlushExample">
        <div class="accordion-body accordion-background">
          <% if @parties == [] %>
            <em>Pas de parties pour le moment.</em>
          <% else %>
            <% @parties.take(5).each do |party| %>
              <div class="party-card card w-80%">
                <% if party.end_time.nil? == false %>
                  <div class="card-header"><%= party.end_time.strftime("Partie jouée le : %d/%m/%Y")%></div>
                  <% party.players.order(:score).reverse.each do |player| %>
                    <ul class="list-group list-group-flush">
                      <li class="list-group-item"><%= player.user.username %> a marqué <%= player.score %> points</li>
                    </ul>
                  <% end %>
                <% end %>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <%# ============= CHALLENGES SECTION =============%>
    <div class="accordion accordion-flush" id="accordionFlushExample">
      <div class="accordion-item">
        <h2 class="accordion-header" id="flush-headingThree">
          <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseThree" aria-expanded="false" aria-controls="flush-collapseThree">
            Défis
          </button>
        </h2>
        <div id="flush-collapseThree" class="accordion-collapse collapse" aria-labelledby="flush-headingThree" data-bs-parent="#accordionFlushExample">
          <div class="accordion-body accordion-background">
            <div class="challenges-container">
              <ul class="mb-3 ms-0 p-0">
                <% @boardgame.challenges.each do |challenge| %>
                  <li class="challenge-card no-bg">🎯 <%= challenge.title %></li>
                  <%#= link_to 'Défi réalisé!', new_user_achievement_path(current_user) %>
                <% end %>
              </ul>
              <div class="ask-new-challenge">
              <% if user_signed_in? %>
                <p><strong class="new-challenge">Proposer un nouveau défi</strong></p>
                <%= render 'challenges/new_form', challenges: @challenge %>
              <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <%# ============= TAGS =============%>
    <div class="accordion accordion-flush" id="accordionFlushExample">
      <div class="accordion-item">
        <h2 class="accordion-header" id="flush-headingFour">
          <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseFour" aria-expanded="false" aria-controls="flush-collapseFour">
            Tags
          </button>
        </h2>
      <div id="flush-collapseFour" class="accordion-collapse collapse" aria-labelledby="flush-headingFour" data-bs-parent="#accordionFlushExample">
        <div class="accordion-body accordion-background">
          <div class="challenges-container">
            <ul class="category-container">
              <% @boardgame.category.split(',').each do |element|  %>
                <span class="category"><%= element %></span>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>